eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true        
server:
    port: 8081
spring:
    application:
        name: Department-service   
    datasource:
        password: Haridiv@1317
        url: jdbc:mysql://localhost:3306/testdb
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
        show-sql: true
